const Actions = {
  SET_LOGGED_IN: 'SET_LOGGED_IN',
  LOGIN: 'LOGIN',
  LOGOUT: 'LOGOUT',
  SET_BOOKS: 'SET_BOOKS',
  ADD_BOOK: 'ADD_BOOK',
  UPDATE_BOOK: 'UPDATE__BOOK',
  DELETE_BOOK: 'DELETE_BOOK'
};

export default Actions;